### ISSUE TITLE
Fix installation policy link in M1

### ISSUE THREAD

**Issue by sethrj** [xsdk-project/xsdk-community-policies#23]
While looking into the XSDK requirements I found that the "installation policies" link in the [M1 package policies document](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M1.md) needs updating to [this page I believe](https://github.com/xsdk-project/xsdk-community-policies/blob/master/installation_policies/1.md).

**Comment by shuds13** [comment]
This should be resolved when #20 is pulled in.
